name: 20.5-Build

on:
  push:
    branches: ["20.5"]
  pull_request:
    branches: ["20.5"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: majobroom
          path: build/libs/*.jar